spring:
  datasource:
    password: 443137c33b29f1f0329b8a3a4dae6c745aaf98d04bd23b9e743fea43e95792ca
    url: jdbc:postgresql://ec2-54-155-92-75.eu-west-1.compute.amazonaws.com:5432/d12g791i3pdtau
    username: penytkaehorcyy
    #    url: jdbc:postgresql://localhost:5432/forum_db
    #    username: postgres
    #    password: mausimj
    platform: POSTGRESQL
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 658706661281-m6jlt4njur0a5ivaj7eflm4kk0qo2pit.apps.googleusercontent.com
            clientSecret: eSuwAWMzpBU2rnM24I0qo_AO
            scope:
                - email
                - profile
          facebook:
            clientId: 1948753795290458
            clientSecret: a6bded606956a843b0460e99409421fe
            scope:
              - email
              - public_profile

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  logging:
    file:
      logs/app.log
  mvc:
    hiddenmethod:
      filter:
        enabled:false
server:
  port: 8081
  error:
    include-message: always
    path: /error

